project_id = "dbrzfjekbfkjathotjcj"

# Public functions that don't require JWT authentication
[functions.handle-share-link]
verify_jwt = false

[functions.get-invitation]
verify_jwt = false

[functions.decline-invitation]
verify_jwt = false

# System template generator functions require admin authentication
[functions.system-template-gen-health]
verify_jwt = true

[functions.system-template-gen-seeds-ingest]
verify_jwt = true

[functions.system-template-gen-seeds-compose]
verify_jwt = true