// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbrzfjekbfkjathotjcj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRicnpmamVrYmZramF0aG90amNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1ODIxOTIsImV4cCI6MjA2NzE1ODE5Mn0.d96Oz9dS1nBffTdTzq33HZTVq0BJBy3Y3xmpvKgwCBI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});