name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Print versions
        run: |
          node -v
          npm -v
          uname -a

      # TEMP: allow npm to resolve Linux optional deps (we'll switch back to `npm ci` after lock regen)
      - name: Install
        run: npm i --no-audit --no-fund

      - name: Build
        run: npm run build

      - name: Test
        run: npm test -- --run --reporter=verbose
